<?php
/**
 * Adds Basic ACF Fields to Site Settings
 *
 * @package WordPress
 * @subpackage vanlig
 * @since 2.1
 * @version 2.1
 */


if( function_exists('acf_add_local_field_group') ):

  acf_add_local_field_group(array (
    'key' => 'group_599062da8e30b',
    'title' => 'Site Settings',
    'fields' => array (
      array (
        'key' => 'field_599062e2f0e29',
        'label' => 'Contact Details',
        'name' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
      ),
      array (
        'key' => 'field_599062f6f0e2a',
        'label' => 'Telephone Number',
        'name' => 'telephone_number',
        'type' => 'number',
        'instructions' => 'Your main Telephone Number',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'min' => '',
        'max' => '',
        'step' => '',
        'readonly' => 0,
        'disabled' => 0,
      ),
      array (
        'key' => 'field_59906300f0e2b',
        'label' => 'Fax Number',
        'name' => 'fax_number',
        'type' => 'number',
        'instructions' => 'Your main Fax number',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'min' => '',
        'max' => '',
        'step' => '',
        'readonly' => 0,
        'disabled' => 0,
      ),
      array (
        'key' => 'field_59906308f0e2c',
        'label' => 'Email Address',
        'name' => 'email_address',
        'type' => 'email',
        'instructions' => 'Your main Email Address',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array (
        'key' => 'field_599063b9f0e2d',
        'label' => 'Address',
        'name' => 'address',
        'type' => 'textarea',
        'instructions' => 'Your Address',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'new_lines' => 'wpautop',
        'readonly' => 0,
        'disabled' => 0,
      ),
      array (
        'key' => 'field_5990644cf0e2e',
        'label' => 'Social Platforms',
        'name' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
      ),
      array (
        'key' => 'field_59906456f0e2f',
        'label' => 'Facebook URL',
        'name' => 'facebook_url',
        'type' => 'url',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
      ),
      array (
        'key' => 'field_59906559f0e30',
        'label' => 'Twitter URL',
        'name' => 'twitter_url',
        'type' => 'url',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
      ),
      array (
        'key' => 'field_59906560f0e31',
        'label' => 'Pinterest URL',
        'name' => 'pinterest_url',
        'type' => 'url',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
      ),
      array (
        'key' => 'field_59906572f0e32',
        'label' => 'Instagram URL',
        'name' => 'instagram_url',
        'type' => 'url',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
      ),
      array (
        'key' => 'field_5990657af0e33',
        'label' => 'Google Plus URL',
        'name' => 'google_plus_url',
        'type' => 'url',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
      ),
      array (
        'key' => 'field_59908002f0e34',
        'label' => 'LinkedIn URL',
        'name' => 'linkedin_url',
        'type' => 'url',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
      ),
      array (
        'key' => 'field_599080af6ac1f',
        'label' => 'YouTube URL',
        'name' => 'youtube_url',
        'type' => 'url',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
      ),
      array (
        'key' => 'field_599080b96ac20',
        'label' => 'Houzz URL',
        'name' => 'houzz_url',
        'type' => 'url',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'theme-settings',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
  ));

  endif;
?>